# Generated by Django 2.0.3 on 2018-04-21 15:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('learning_logs', '0003_auto_20180420_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='groups',
        ),
    ]
